import React, { useState, useEffect } from "react";
import Head from "next/head";

import ProfileComp from "../../../src/components/Profile/ProfileComp";

function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: undefined,
    height: undefined,
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      function handleResize() {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      }
      window.addEventListener("resize", handleResize);
      handleResize();
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []);
  return windowSize;
}

const Profile = () => {
  const size = useWindowSize();
  const [addresses, setAddresses] = useState({});

  return (
    <>
      <Head>
        <title>My Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoMini.png" />
      </Head>

      <div>
        <div style={{ marginTop: "20px" }}>
          <ProfileComp addresses={addresses} />
        </div>
      </div>
    </>
  );
};

export default Profile;

// export const getServerSideProps = async (context) => {
//   const resAddress = await get_address_by_user_id(1);
//   const addresses = resAddress.data.data;

//   return {
//     props: {
//       addresses,
//     },
//   };
// };
