import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DashBoard from "../src/components/Dashboard/DashBoard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="Admin Panel" content="Generated by create next app" />
        <link rel="icon" href="/LogoMini.png" />
      </Head>

      <div style={{padding: 0}}>
        <DashBoard />
      </div>
    </>
  );
}
